# Generated by Django 2.2.2 on 2019-06-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_average_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_average_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_average_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_average_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age_of_majority', models.IntegerField()),
                ('basic_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RacePlayingFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('YOUR', 'Вы скорее всего...'), ('OTHER', 'Другие расы скорее всего...')], default='YOUR', max_length=255)),
                ('text', models.TextField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playingforinformations', to='starfinder.Race')),
            ],
        ),
        migrations.CreateModel(
            name='RaceDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='starfinder.Race')),
            ],
        ),
    ]
