# Generated by Django 2.2.2 on 2019-06-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='title_info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
