# Generated by Django 2.2.2 on 2019-06-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0002_race_title_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='basic_image',
            field=models.ImageField(blank=True, null=True, upload_to='races/'),
        ),
        migrations.AddField(
            model_name='race',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='races/'),
        ),
    ]
