# Generated by Django 2.2.2 on 2019-06-26 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import starfinder.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('starfinder', '0004_subrace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawfull_chaotic', models.CharField(choices=[(0, 'Принципиальный'), (1, 'Нейтральный'), (2, 'Хаотичный')], default=1, max_length=15)),
                ('good_evil', models.CharField(choices=[(0, 'Добрый'), (1, 'Нейтральный'), (2, 'Злой')], default=1, max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'unique_together': {('lawfull_chaotic', 'good_evil')},
            },
        ),
        migrations.CreateModel(
            name='GameClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('basic_info', models.TextField()),
                ('title_info', models.TextField()),
                ('basic_image', models.ImageField(blank=True, null=True, upload_to='classes/')),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='classes/')),
                ('main_ability', models.CharField(choices=[(starfinder.models.AbilityChoice('Сила'), 'Сила'), (starfinder.models.AbilityChoice('Ловкость'), 'Ловкость'), (starfinder.models.AbilityChoice('Выносливость'), 'Выносливость'), (starfinder.models.AbilityChoice('Интеллект'), 'Интеллект'), (starfinder.models.AbilityChoice('Мудрость'), 'Мудрость'), (starfinder.models.AbilityChoice('Харизма'), 'Харизма')], max_length=5, null=True)),
                ('hit_points_on_level', models.IntegerField()),
                ('stamina_point_on_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ability', models.CharField(choices=[(starfinder.models.AbilityChoice('Сила'), 'Сила'), (starfinder.models.AbilityChoice('Ловкость'), 'Ловкость'), (starfinder.models.AbilityChoice('Выносливость'), 'Выносливость'), (starfinder.models.AbilityChoice('Интеллект'), 'Интеллект'), (starfinder.models.AbilityChoice('Мудрость'), 'Мудрость'), (starfinder.models.AbilityChoice('Харизма'), 'Харизма')], max_length=5, null=True)),
                ('without_learning', models.BooleanField(default=True)),
                ('armor_penalty_applies', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('need_additional_info', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('basic_info', models.TextField()),
                ('title_info', models.TextField()),
                ('basic_image', models.ImageField(blank=True, null=True, upload_to='themes/')),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='themes/')),
                ('base_ability', models.CharField(choices=[(starfinder.models.AbilityChoice('Сила'), 'Сила'), (starfinder.models.AbilityChoice('Ловкость'), 'Ловкость'), (starfinder.models.AbilityChoice('Выносливость'), 'Выносливость'), (starfinder.models.AbilityChoice('Интеллект'), 'Интеллект'), (starfinder.models.AbilityChoice('Мудрость'), 'Мудрость'), (starfinder.models.AbilityChoice('Харизма'), 'Харизма')], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('portfolios', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='deities/')),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='starfinder.Alignment')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='character_portraits/')),
                ('sex', models.CharField(choices=[(starfinder.models.SexChoice('Мужской'), 'Мужской'), (starfinder.models.SexChoice('Женский'), 'Женский')], max_length=5)),
                ('description', models.TextField()),
                ('сharacteristic_pool', models.IntegerField(default=0)),
                ('skill_points_pool', models.IntegerField(default=0)),
                ('level', models.IntegerField()),
                ('basic_attack_bonus', models.IntegerField()),
                ('basic_fortitude', models.IntegerField()),
                ('basic_reflex', models.IntegerField()),
                ('basic_will', models.IntegerField()),
                ('hit_points', models.IntegerField()),
                ('stamina_points', models.IntegerField()),
                ('resolve_points', models.IntegerField()),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='starfinder.Alignment')),
                ('deity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starfinder.Deity')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='starfinder.Race')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='starfinder.Theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkillValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_learned', models.BooleanField()),
                ('skill_points', models.IntegerField()),
                ('additional_info', models.CharField(max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillvalues', to='starfinder.Character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='starfinder.Skill')),
            ],
            options={
                'unique_together': {('character', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='CharacterGameClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameclasses', to='starfinder.Character')),
                ('game_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='starfinder.GameClass')),
            ],
            options={
                'unique_together': {('character', 'game_class')},
            },
        ),
        migrations.CreateModel(
            name='AbilityValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(choices=[(starfinder.models.AbilityChoice('Сила'), 'Сила'), (starfinder.models.AbilityChoice('Ловкость'), 'Ловкость'), (starfinder.models.AbilityChoice('Выносливость'), 'Выносливость'), (starfinder.models.AbilityChoice('Интеллект'), 'Интеллект'), (starfinder.models.AbilityChoice('Мудрость'), 'Мудрость'), (starfinder.models.AbilityChoice('Харизма'), 'Харизма')], max_length=5)),
                ('value', models.IntegerField()),
                ('temp_value', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilityvalues', to='starfinder.Character')),
            ],
            options={
                'unique_together': {('character', 'ability')},
            },
        ),
    ]
