# Generated by Django 2.2.2 on 2019-06-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0007_auto_20190627_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameclass',
            name='skill_point_on_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameclass',
            name='main_ability',
            field=models.CharField(choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('Int', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='ability',
            field=models.CharField(choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('Int', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='base_ability',
            field=models.CharField(blank=True, choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('Int', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255, null=True),
        ),
    ]
