# Generated by Django 2.2.2 on 2019-07-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0008_auto_20190627_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='сharacteristic_pool',
            new_name='ability_pool',
        ),
        migrations.RemoveField(
            model_name='character',
            name='sex',
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Femail', 'Женский')], default='Male', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abilityvalue',
            name='ability',
            field=models.CharField(choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('Int', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255),
        ),
        migrations.CreateModel(
            name='ThemeRulesActingOnCharLevelUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField()),
                ('ability', models.CharField(blank=True, choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('Int', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255, null=True)),
                ('character_property', models.CharField(blank=True, choices=[('basic_attack_bonus', 'Базовый модификатор атаки'), ('basic_fortitude', 'Базовая стойкость'), ('basic_reflex', 'Базовая реакция'), ('basic_will', 'Базовая воля'), ('hit_points', 'Пункты здоровья'), ('stamina_points', 'Пункты живучести'), ('resolve_points', 'Пункты решимости'), ('ability_pool', 'Очки характеристик доступные для распределения'), ('skill_points_pool', 'Очки навыков доступные для распределения')], max_length=255, null=True)),
                ('change_to', models.IntegerField()),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='starfinder.Skill')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesactingoncharlevelup', to='starfinder.Theme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaceRulesActingOnCharLevelUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField()),
                ('ability', models.CharField(blank=True, choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('Int', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255, null=True)),
                ('character_property', models.CharField(blank=True, choices=[('basic_attack_bonus', 'Базовый модификатор атаки'), ('basic_fortitude', 'Базовая стойкость'), ('basic_reflex', 'Базовая реакция'), ('basic_will', 'Базовая воля'), ('hit_points', 'Пункты здоровья'), ('stamina_points', 'Пункты живучести'), ('resolve_points', 'Пункты решимости'), ('ability_pool', 'Очки характеристик доступные для распределения'), ('skill_points_pool', 'Очки навыков доступные для распределения')], max_length=255, null=True)),
                ('change_to', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesactingoncharlevelup', to='starfinder.Race')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='starfinder.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassRulesActingOnCharLevelUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField()),
                ('ability', models.CharField(blank=True, choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('Int', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255, null=True)),
                ('character_property', models.CharField(blank=True, choices=[('basic_attack_bonus', 'Базовый модификатор атаки'), ('basic_fortitude', 'Базовая стойкость'), ('basic_reflex', 'Базовая реакция'), ('basic_will', 'Базовая воля'), ('hit_points', 'Пункты здоровья'), ('stamina_points', 'Пункты живучести'), ('resolve_points', 'Пункты решимости'), ('ability_pool', 'Очки характеристик доступные для распределения'), ('skill_points_pool', 'Очки навыков доступные для распределения')], max_length=255, null=True)),
                ('change_to', models.IntegerField()),
                ('game_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesactingoncharlevelup', to='starfinder.GameClass')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='starfinder.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
