# Generated by Django 2.2.2 on 2019-07-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0009_auto_20190706_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='basic_attack_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='basic_fortitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='basic_reflex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='basic_will',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='resolve_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='stamina_points',
            field=models.IntegerField(default=0),
        ),
    ]
