# Generated by Django 2.2.2 on 2019-07-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0010_auto_20190708_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrulesactingoncharlevelup',
            name='operation',
            field=models.CharField(blank=True, choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('INT', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='racerulesactingoncharlevelup',
            name='operation',
            field=models.CharField(blank=True, choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('INT', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='themerulesactingoncharlevelup',
            name='operation',
            field=models.CharField(blank=True, choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('INT', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abilityvalue',
            name='ability',
            field=models.CharField(choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('INT', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255),
        ),
        migrations.AlterField(
            model_name='classrulesactingoncharlevelup',
            name='ability',
            field=models.CharField(blank=True, choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('INT', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gameclass',
            name='main_ability',
            field=models.CharField(choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('INT', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255),
        ),
        migrations.AlterField(
            model_name='racerulesactingoncharlevelup',
            name='ability',
            field=models.CharField(blank=True, choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('INT', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='ability',
            field=models.CharField(choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('INT', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='base_ability',
            field=models.CharField(blank=True, choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('INT', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='themerulesactingoncharlevelup',
            name='ability',
            field=models.CharField(blank=True, choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('INT', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255, null=True),
        ),
    ]
