# Generated by Django 2.2.2 on 2019-07-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0011_auto_20190709_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrulesactingoncharlevelup',
            name='operation',
            field=models.CharField(blank=True, choices=[('Add', 'Прибавить'), ('Set', 'Установить')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='racerulesactingoncharlevelup',
            name='operation',
            field=models.CharField(blank=True, choices=[('Add', 'Прибавить'), ('Set', 'Установить')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='themerulesactingoncharlevelup',
            name='operation',
            field=models.CharField(blank=True, choices=[('Add', 'Прибавить'), ('Set', 'Установить')], max_length=255, null=True),
        ),
    ]
