# Generated by Django 2.2.2 on 2019-07-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0013_auto_20190709_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
