# Generated by Django 2.2.2 on 2019-07-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0014_auto_20190717_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='distributed_skill_points',
            field=models.IntegerField(default=0),
        ),
    ]
