# Generated by Django 2.2.2 on 2019-07-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0015_character_distributed_skill_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterskillvalue',
            name='class_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='characterskillvalue',
            name='additional_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
