# Generated by Django 2.2.2 on 2019-08-08 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0016_auto_20190730_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('byname', models.CharField(blank=True, max_length=255, null=True)),
                ('diam', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('gravity', models.CharField(max_length=255)),
                ('air', models.IntegerField(choices=[(0, 'Отсутствует'), (1, 'Разряжённая'), (2, 'Обычная'), (3, 'Особая'), (4, 'Токсичная и разряжённая'), (5, 'Обычная или отсутствует'), (6, 'Токсичная')], default=2)),
                ('day', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('described', models.TextField()),
                ('planet_image', models.ImageField(blank=True, null=True, upload_to='world/')),
                ('panoramic_image', models.ImageField(blank=True, null=True, upload_to='world/')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='subrace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starfinder.Subrace'),
        ),
        migrations.CreateModel(
            name='ThemeClassSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='starfinder.Skill')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_class_skill_rules', to='starfinder.Theme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubRaceRulesActingOnCharLevelUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField()),
                ('ability', models.CharField(blank=True, choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('INT', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255, null=True)),
                ('character_property', models.CharField(blank=True, choices=[('basic_attack_bonus', 'Базовый модификатор атаки'), ('basic_fortitude', 'Базовая стойкость'), ('basic_reflex', 'Базовая реакция'), ('basic_will', 'Базовая воля'), ('hit_points', 'Пункты здоровья'), ('stamina_points', 'Пункты живучести'), ('resolve_points', 'Пункты решимости'), ('ability_pool', 'Очки характеристик доступные для распределения'), ('skill_points_pool', 'Очки навыков доступные для распределения')], max_length=255, null=True)),
                ('change_to', models.IntegerField()),
                ('operation', models.CharField(blank=True, choices=[('Add', 'Прибавить'), ('Set', 'Установить')], max_length=255, null=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='starfinder.Skill')),
                ('subrace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesactingoncharlevelup', to='starfinder.Subrace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('game_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_class_skill_rules', to='starfinder.GameClass')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='starfinder.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='character',
            name='home_world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starfinder.World'),
        ),
    ]
