# Generated by Django 2.2.2 on 2019-08-21 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0019_auto_20190817_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bulk', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CriticalEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discription', models.TextField(blank=True, null=True)),
                ('armor_damage_type', models.CharField(choices=[('EAC', 'ЭКБ'), ('KAC', 'ККБ'), ('EAC_KAC', 'ЭКБ & ККБ')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='subrace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starfinder.Subrace'),
        ),
        migrations.AlterField(
            model_name='subracerulesactingoncharlevelup',
            name='subrace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesactingoncharlevelup', to='starfinder.Subrace'),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('baseequipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='starfinder.BaseEquipment')),
                ('count_hand', models.IntegerField()),
                ('damage_dice_count', models.IntegerField(blank=True, null=True)),
                ('damage_dice_type', models.CharField(choices=[('D3', 'd3'), ('D4', 'd4'), ('D6', 'd6'), ('D8', 'd8'), ('D10', 'd10'), ('D12', 'd12'), ('D20', 'd20'), ('D100', 'd100')], max_length=255)),
                ('critical_dice_count', models.IntegerField(blank=True, null=True)),
                ('critical_dice_type', models.CharField(choices=[('D3', 'd3'), ('D4', 'd4'), ('D6', 'd6'), ('D8', 'd8'), ('D10', 'd10'), ('D12', 'd12'), ('D20', 'd20'), ('D100', 'd100')], max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='starfinder.WeaponCategory')),
                ('critical_effect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='starfinder.CriticalEffect')),
                ('secial', models.ManyToManyField(to='starfinder.WeaponSpecial')),
                ('weapon_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='starfinder.WeaponType')),
            ],
            bases=('starfinder.baseequipment',),
        ),
    ]
