# Generated by Django 2.2.2 on 2019-08-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0021_auto_20190821_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='subrace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starfinder.Subrace'),
        ),
        migrations.AlterField(
            model_name='subracerulesactingoncharlevelup',
            name='subrace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesactingoncharlevelup', to='starfinder.Subrace'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='critical_dice_type',
            field=models.CharField(blank=True, choices=[('D3', 'd3'), ('D4', 'd4'), ('D6', 'd6'), ('D8', 'd8'), ('D10', 'd10'), ('D12', 'd12'), ('D20', 'd20'), ('D100', 'd100')], max_length=255, null=True),
        ),
    ]
