# Generated by Django 2.2.2 on 2019-09-05 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0022_auto_20190821_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='secial',
            new_name='special',
        ),
        migrations.RenameField(
            model_name='weaponcategory',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='weaponspecial',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='weapontype',
            old_name='discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='criticaleffect',
            name='discription',
        ),
        migrations.AddField(
            model_name='criticaleffect',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='subrace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starfinder.Subrace'),
        ),
        migrations.AlterField(
            model_name='subracerulesactingoncharlevelup',
            name='subrace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesactingoncharlevelup', to='starfinder.Subrace'),
        ),
    ]
