# Generated by Django 2.2.2 on 2019-10-08 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0024_auto_20190905_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('baseequipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='starfinder.BaseEquipment')),
                ('type_armor', models.CharField(blank=True, choices=[('light', 'Легкая броня'), ('heavy', 'Тяжелая броня')], max_length=255)),
                ('eac', models.IntegerField()),
                ('kac', models.IntegerField()),
                ('armor_check_penalty', models.IntegerField()),
                ('speed_adjustment', models.IntegerField()),
                ('upgrade_slots', models.IntegerField()),
                ('max_dex', models.IntegerField()),
            ],
            bases=('starfinder.baseequipment',),
        ),
        migrations.AlterField(
            model_name='character',
            name='subrace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starfinder.Subrace'),
        ),
        migrations.AlterField(
            model_name='subracerulesactingoncharlevelup',
            name='subrace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesactingoncharlevelup', to='starfinder.Subrace'),
        ),
    ]
