# Generated by Django 2.2.2 on 2019-12-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starfinder', '0028_auto_20191010_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='experience_to_level_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='subrace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starfinder.Subrace'),
        ),
        migrations.AlterField(
            model_name='classrulesactingoncharlevelup',
            name='character_property',
            field=models.CharField(blank=True, choices=[('basic_attack_bonus', 'Базовый модификатор атаки'), ('basic_fortitude', 'Базовая стойкость'), ('basic_reflex', 'Базовая реакция'), ('basic_will', 'Базовая воля'), ('hit_points', 'Пункты здоровья'), ('stamina_points', 'Пункты живучести'), ('resolve_points', 'Пункты решимости'), ('ability_pool', 'Очки характеристик доступные для распределения'), ('skill_points_pool', 'Очки навыков доступные для распределения'), ('feats_pool', 'Количество черт доступных для выбора'), ('experience_to_level_up', 'Опыт для повышения уровня')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='featprerequest',
            name='character_property',
            field=models.CharField(blank=True, choices=[('basic_attack_bonus', 'Базовый модификатор атаки'), ('basic_fortitude', 'Базовая стойкость'), ('basic_reflex', 'Базовая реакция'), ('basic_will', 'Базовая воля'), ('hit_points', 'Пункты здоровья'), ('stamina_points', 'Пункты живучести'), ('resolve_points', 'Пункты решимости'), ('ability_pool', 'Очки характеристик доступные для распределения'), ('skill_points_pool', 'Очки навыков доступные для распределения'), ('feats_pool', 'Количество черт доступных для выбора'), ('experience_to_level_up', 'Опыт для повышения уровня')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='racerulesactingoncharlevelup',
            name='character_property',
            field=models.CharField(blank=True, choices=[('basic_attack_bonus', 'Базовый модификатор атаки'), ('basic_fortitude', 'Базовая стойкость'), ('basic_reflex', 'Базовая реакция'), ('basic_will', 'Базовая воля'), ('hit_points', 'Пункты здоровья'), ('stamina_points', 'Пункты живучести'), ('resolve_points', 'Пункты решимости'), ('ability_pool', 'Очки характеристик доступные для распределения'), ('skill_points_pool', 'Очки навыков доступные для распределения'), ('feats_pool', 'Количество черт доступных для выбора'), ('experience_to_level_up', 'Опыт для повышения уровня')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subracerulesactingoncharlevelup',
            name='character_property',
            field=models.CharField(blank=True, choices=[('basic_attack_bonus', 'Базовый модификатор атаки'), ('basic_fortitude', 'Базовая стойкость'), ('basic_reflex', 'Базовая реакция'), ('basic_will', 'Базовая воля'), ('hit_points', 'Пункты здоровья'), ('stamina_points', 'Пункты живучести'), ('resolve_points', 'Пункты решимости'), ('ability_pool', 'Очки характеристик доступные для распределения'), ('skill_points_pool', 'Очки навыков доступные для распределения'), ('feats_pool', 'Количество черт доступных для выбора'), ('experience_to_level_up', 'Опыт для повышения уровня')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subracerulesactingoncharlevelup',
            name='subrace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesactingoncharlevelup', to='starfinder.Subrace'),
        ),
        migrations.AlterField(
            model_name='themerulesactingoncharlevelup',
            name='character_property',
            field=models.CharField(blank=True, choices=[('basic_attack_bonus', 'Базовый модификатор атаки'), ('basic_fortitude', 'Базовая стойкость'), ('basic_reflex', 'Базовая реакция'), ('basic_will', 'Базовая воля'), ('hit_points', 'Пункты здоровья'), ('stamina_points', 'Пункты живучести'), ('resolve_points', 'Пункты решимости'), ('ability_pool', 'Очки характеристик доступные для распределения'), ('skill_points_pool', 'Очки навыков доступные для распределения'), ('feats_pool', 'Количество черт доступных для выбора'), ('experience_to_level_up', 'Опыт для повышения уровня')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='GeneralRulesOnCharLevelUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField()),
                ('ability', models.CharField(blank=True, choices=[('STR', 'Сила'), ('DEX', 'Ловкость'), ('CON', 'Выносливость'), ('INT', 'Интеллект'), ('WIS', 'Мудрость'), ('CHA', 'Харизма')], max_length=255, null=True)),
                ('character_property', models.CharField(blank=True, choices=[('basic_attack_bonus', 'Базовый модификатор атаки'), ('basic_fortitude', 'Базовая стойкость'), ('basic_reflex', 'Базовая реакция'), ('basic_will', 'Базовая воля'), ('hit_points', 'Пункты здоровья'), ('stamina_points', 'Пункты живучести'), ('resolve_points', 'Пункты решимости'), ('ability_pool', 'Очки характеристик доступные для распределения'), ('skill_points_pool', 'Очки навыков доступные для распределения'), ('feats_pool', 'Количество черт доступных для выбора'), ('experience_to_level_up', 'Опыт для повышения уровня')], max_length=255, null=True)),
                ('change_to', models.IntegerField()),
                ('operation', models.CharField(blank=True, choices=[('Add', 'Прибавить'), ('Set', 'Установить')], max_length=255, null=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='starfinder.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
